# Generated by Django 2.0.1 on 2018-02-16 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitCoin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateField(verbose_name='Date of Price')),
                ('open', models.FloatField(default=0.0)),
                ('close', models.FloatField(default=0.0)),
                ('high', models.FloatField(default=0.0)),
                ('low', models.FloatField(default=0.0)),
                ('volume', models.FloatField(default=0.0)),
                ('market_cap', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='CryptoCompareCoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xchange_coin', models.IntegerField(default=1)),
                ('url', models.CharField(default='', max_length=200)),
                ('image_url', models.CharField(default='', max_length=200)),
                ('name', models.CharField(default='', max_length=50)),
                ('symbol', models.CharField(default='', max_length=10)),
                ('coin_name', models.CharField(default='', max_length=50)),
                ('full_name', models.CharField(default='', max_length=100)),
                ('algorithm', models.CharField(default='', max_length=50)),
                ('proof_type', models.CharField(default='', max_length=50)),
                ('fully_premined', models.SmallIntegerField(default=1)),
                ('total_coin_supply', models.FloatField(default=0.0)),
                ('pre_mined_value', models.CharField(default='', max_length=20)),
                ('total_coins_free_float', models.CharField(default='', max_length=20)),
                ('sort_order', models.SmallIntegerField(default=1)),
                ('sponsored', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Xchange',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('url', models.CharField(default='', max_length=200)),
                ('api_url', models.CharField(default='', max_length=200)),
                ('api_key', models.CharField(default='', max_length=200)),
                ('api_secret', models.CharField(default='', max_length=200)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='cryptocomparecoin',
            name='xchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Xchange'),
        ),
        migrations.AddField(
            model_name='bitcoin',
            name='xchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Xchange'),
        ),
    ]
