# Generated by Django 2.0.1 on 2018-02-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Xchange',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('url', models.CharField(default='0', max_length=200, unique=True)),
                ('api_url', models.CharField(default='0', max_length=200)),
                ('api_key', models.CharField(default='0', max_length=200)),
                ('api_secret', models.CharField(default='0', max_length=200)),
                ('start_date', models.BigIntegerField(default=0, verbose_name='start date')),
                ('end_date', models.BigIntegerField(default=0, verbose_name='end date')),
                ('number_symbols', models.IntegerField(default=0, verbose_name='number of symbols')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
