# Generated by Django 2.0.1 on 2018-02-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimeCoins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
