# Generated by Django 2.0.1 on 2018-02-16 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimeCoins', '0002_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitcoin',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bitcoin',
            name='time',
            field=models.BigIntegerField(default=0, verbose_name='Date of Price'),
        ),
    ]
