# Generated by Django 2.0.1 on 2018-02-17 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimeCoins', '0005_auto_20180216_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='btc',
            options={},
        ),
        migrations.AlterField(
            model_name='coin',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
    ]
