# Generated by Django 2.0.1 on 2018-02-17 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimeCoins', '0007_auto_20180217_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTC',
            fields=[
                ('coin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DimeCoins.Coin')),
            ],
            bases=('DimeCoins.coin',),
        ),
        migrations.AlterField(
            model_name='coin',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
    ]
