# Generated by Django 2.0.1 on 2018-02-17 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimeCoins', '0008_auto_20180217_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='btc',
            name='coin_ptr',
        ),
        migrations.AlterField(
            model_name='coin',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.DeleteModel(
            name='BTC',
        ),
    ]
