# Generated by Django 2.0.1 on 2018-02-17 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimeCoins', '0011_auto_20180217_0938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ada',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bch',
            options={},
        ),
        migrations.AlterModelOptions(
            name='btg',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dash',
            options={},
        ),
        migrations.AlterModelOptions(
            name='doge',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dsh',
            options={},
        ),
        migrations.AlterModelOptions(
            name='eos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='etc',
            options={},
        ),
        migrations.AlterModelOptions(
            name='eth',
            options={},
        ),
        migrations.AlterModelOptions(
            name='icn',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lsk',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ltc',
            options={},
        ),
        migrations.AlterModelOptions(
            name='maid',
            options={},
        ),
        migrations.AlterModelOptions(
            name='miota',
            options={},
        ),
        migrations.AlterModelOptions(
            name='neo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='omgc',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rep',
            options={},
        ),
        migrations.AlterModelOptions(
            name='steem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='waves',
            options={},
        ),
        migrations.AlterModelOptions(
            name='xem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='xmr',
            options={},
        ),
        migrations.AlterModelOptions(
            name='xrp',
            options={},
        ),
        migrations.AlterModelOptions(
            name='zec',
            options={},
        ),
        migrations.AlterField(
            model_name='ada',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='bch',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='btc',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='btg',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='dash',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='doge',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='dsh',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='eos',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='etc',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='eth',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='icn',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='lsk',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='ltc',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='maid',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='miota',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='neo',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='omgc',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='rep',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='steem',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='waves',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='xem',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='xmr',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='xrp',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='zec',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
    ]
