# Generated by Django 2.0.1 on 2018-02-25 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimeCoins', '0014_tkn_tkr_tks_tkt_tky_tle_tmc_tme_tmt_tnb_tnc_tnd_tnt_toa_today_tok_tokc_token_tom_top_topaz_topc_tor_'),
    ]

    operations = [
        migrations.CreateModel(
            name='XDG',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.BigIntegerField(default=0, verbose_name='Date of Price')),
                ('open', models.FloatField(default=0.0)),
                ('close', models.FloatField(default=0.0)),
                ('high', models.FloatField(default=0.0)),
                ('low', models.FloatField(default=0.0)),
                ('total_supply', models.FloatField(default=0.0)),
                ('volume', models.FloatField(default=0.0)),
                ('market_cap', models.FloatField(default=0.0)),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='DimeCoins.Currency')),
                ('xchange', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='DimeCoins.Xchange')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='XVN',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.BigIntegerField(default=0, verbose_name='Date of Price')),
                ('open', models.FloatField(default=0.0)),
                ('close', models.FloatField(default=0.0)),
                ('high', models.FloatField(default=0.0)),
                ('low', models.FloatField(default=0.0)),
                ('total_supply', models.FloatField(default=0.0)),
                ('volume', models.FloatField(default=0.0)),
                ('market_cap', models.FloatField(default=0.0)),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='DimeCoins.Currency')),
                ('xchange', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='DimeCoins.Xchange')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
