# Generated by Django 2.0.1 on 2018-02-17 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimeCoins', '0016_auto_20180217_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCompare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xchange_coin', models.IntegerField(default=1)),
                ('name', models.CharField(default='', max_length=50)),
                ('symbol', models.CharField(default='', max_length=10)),
                ('total_coin_supply', models.FloatField(default=0.0)),
                ('total_coins_free_float', models.CharField(default='', max_length=20)),
                ('xchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Xchange')),
            ],
        ),
        migrations.RemoveField(
            model_name='cryptocomparecoin',
            name='xchange',
        ),
        migrations.AlterField(
            model_name='ada',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='bch',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='btc',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='btg',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='dash',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='doge',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='dsh',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='eos',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='etc',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='eth',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='icn',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='iota',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='lsk',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='ltc',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='maid',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='miota',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='neo',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='omgc',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='rep',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='steem',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='waves',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='xem',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='xmr',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='xrp',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='zec',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.DeleteModel(
            name='CryptoCompareCoin',
        ),
    ]
