# Generated by Django 2.0.1 on 2018-02-21 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DimeCoins', '0022_auto_20180220_1232'),
        ('DimeCoins', '0021_auto_20180221_1327'),
    ]

    operations = [
    ]
