# Generated by Django 2.0.1 on 2018-02-25 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimeCoins', '0025_uniburst'),
    ]

    operations = [
        migrations.CreateModel(
            name='BRXT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.BigIntegerField(default=0, verbose_name='Date of Price')),
                ('open', models.FloatField(default=0.0)),
                ('close', models.FloatField(default=0.0)),
                ('high', models.FloatField(default=0.0)),
                ('low', models.FloatField(default=0.0)),
                ('total_supply', models.FloatField(default=0.0)),
                ('volume', models.FloatField(default=0.0)),
                ('market_cap', models.FloatField(default=0.0)),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='DimeCoins.Currency')),
                ('xchange', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='DimeCoins.Xchange')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JAY',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.BigIntegerField(default=0, verbose_name='Date of Price')),
                ('open', models.FloatField(default=0.0)),
                ('close', models.FloatField(default=0.0)),
                ('high', models.FloatField(default=0.0)),
                ('low', models.FloatField(default=0.0)),
                ('total_supply', models.FloatField(default=0.0)),
                ('volume', models.FloatField(default=0.0)),
                ('market_cap', models.FloatField(default=0.0)),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='DimeCoins.Currency')),
                ('xchange', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='DimeCoins.Xchange')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KUMA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.BigIntegerField(default=0, verbose_name='Date of Price')),
                ('open', models.FloatField(default=0.0)),
                ('close', models.FloatField(default=0.0)),
                ('high', models.FloatField(default=0.0)),
                ('low', models.FloatField(default=0.0)),
                ('total_supply', models.FloatField(default=0.0)),
                ('volume', models.FloatField(default=0.0)),
                ('market_cap', models.FloatField(default=0.0)),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='DimeCoins.Currency')),
                ('xchange', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='DimeCoins.Xchange')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NOC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.BigIntegerField(default=0, verbose_name='Date of Price')),
                ('open', models.FloatField(default=0.0)),
                ('close', models.FloatField(default=0.0)),
                ('high', models.FloatField(default=0.0)),
                ('low', models.FloatField(default=0.0)),
                ('total_supply', models.FloatField(default=0.0)),
                ('volume', models.FloatField(default=0.0)),
                ('market_cap', models.FloatField(default=0.0)),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='DimeCoins.Currency')),
                ('xchange', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='DimeCoins.Xchange')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PFC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.BigIntegerField(default=0, verbose_name='Date of Price')),
                ('open', models.FloatField(default=0.0)),
                ('close', models.FloatField(default=0.0)),
                ('high', models.FloatField(default=0.0)),
                ('low', models.FloatField(default=0.0)),
                ('total_supply', models.FloatField(default=0.0)),
                ('volume', models.FloatField(default=0.0)),
                ('market_cap', models.FloatField(default=0.0)),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='DimeCoins.Currency')),
                ('xchange', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='DimeCoins.Xchange')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TTY',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.BigIntegerField(default=0, verbose_name='Date of Price')),
                ('open', models.FloatField(default=0.0)),
                ('close', models.FloatField(default=0.0)),
                ('high', models.FloatField(default=0.0)),
                ('low', models.FloatField(default=0.0)),
                ('total_supply', models.FloatField(default=0.0)),
                ('volume', models.FloatField(default=0.0)),
                ('market_cap', models.FloatField(default=0.0)),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='DimeCoins.Currency')),
                ('xchange', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='DimeCoins.Xchange')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
