# Generated by Django 2.0.1 on 2018-02-22 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimeCoins', '0026_auto_20180221_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='ada',
            name='total_supply',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bch',
            name='total_supply',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='btc',
            name='total_supply',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='btg',
            name='total_supply',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='crix',
            name='total_supply',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dash',
            name='total_supply',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='doge',
            name='total_supply',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dsh',
            name='total_supply',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='eos',
            name='total_supply',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='etc',
            name='total_supply',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='eth',
            name='total_supply',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='icn',
            name='total_supply',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='iota',
            name='total_supply',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='lsk',
            name='total_supply',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ltc',
            name='total_supply',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='maid',
            name='total_supply',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='miota',
            name='total_supply',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='neo',
            name='total_supply',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='omgc',
            name='total_supply',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='rep',
            name='total_supply',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='steem',
            name='total_supply',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='waves',
            name='total_supply',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='xem',
            name='total_supply',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='xlm',
            name='total_supply',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='xmr',
            name='total_supply',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='xrp',
            name='total_supply',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='zec',
            name='total_supply',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ada',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='bch',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='btc',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='btg',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='crix',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='dash',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='doge',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='dsh',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='eos',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='etc',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='eth',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='icn',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='iota',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='lsk',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='ltc',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='maid',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='miota',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='neo',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='omgc',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='rep',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='steem',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='waves',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='xem',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='xlm',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='xmr',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='xrp',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
        migrations.AlterField(
            model_name='zec',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeCoins.Currency'),
        ),
    ]
