# Generated by Django 2.0.1 on 2018-03-04 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimeCoins', '0026_brxt_jay_kuma_noc_pfc_tty'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopCoins',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.BigIntegerField(default=0, verbose_name='Date of Price')),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='DimeCoins.Currency')),
                ('xchange', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='DimeCoins.Xchange')),
            ],
            options={
                'ordering': ('currency',),
            },
        ),
    ]
