# Generated by Django 2.0.1 on 2018-03-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimeCoins', '0027_topcoins'),
    ]

    operations = [
        migrations.AddField(
            model_name='topcoins',
            name='market_cap',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='topcoins',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='topcoins',
            name='total_supply',
            field=models.BigIntegerField(default=0),
        ),
    ]
